# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('own_blog', '0002_auto_20180826_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=64)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='own_blog.Post')),
            ],
        ),
    ]
